// i18n.js — zh/en 全量文案字典 + 语言检测/持久化
// 无 DOM 依赖（document/localStorage/navigator 均带 guard），node 可单测

export const DICT = {
  zh: {
    seoTitle: 'botu — 角色图生成极简 Bot Icon · 免费在线机器人图标生成器',
    appTitle: 'botu',
    langBtn: 'EN',
    tagline: '把任意角色图变成极简 bot icon',
    subTagline: 'AI 图生图 · 保留发型轮廓、标志配色与关键配饰 · 约 3-4 分钟出图',
    dropTitle: '拖拽 / 粘贴 / 点击选择角色图',
    dropHint: '支持 JPEG · PNG · WebP',
    dropActive: '松开即载入',
    beforeLabel: '原图',
    afterLabel: 'bot icon',
    idleHint: '点击「生成图标」开始',
    generate: '生成图标',
    regenerate: '再生成',
    download: '下载 PNG',
    newImage: '换一张',
    loadingNote: '生成约需 3-4 分钟，请不要关闭页面',
    elapsedFmt: '已等待 {s} 秒',
    loadingHints: [
      '正在理解角色特征…',
      '保留发型轮廓与标志配色中…',
      '把可爱浓缩成圆角方块…',
      '快好了，最后打磨中…',
    ],
    fileMetaFmt: '{w}×{h} · {kb} KB',
    errRead: '读取图片失败，请换一张试试',
    errType: '仅支持 JPEG / PNG / WebP 图片',
    err400: '请求无效（400）：图片格式不支持或参数错误',
    err413: '图片太大（413）：请换一张小一点的图',
    err500: '服务未配置（500）：缺少生成密钥',
    err502: '生成失败（502）：上游服务异常，请稍后重试',
    errNetwork: '网络异常或超时：请检查连接后重试',
    errGeneric: '生成出错：{msg}',
    err429: '今日生成次数已用完（每 IP 每天 {max} 次），请明天再试',
    themeAriaToLight: '切换到浅色主题',
    themeAriaToDark: '切换到深色主题',
    quotaFmt: '今日剩余 {n}/{max} 次',
    quotaOut: '今日 {max} 次已用完 — 明天再来（按 UTC 计）',
    galleryTitle: '画廊 · 效果一览',
    gallerySub: '左边是原始角色图，右边是 botu 生成的极简 bot icon',
    cap1: '橘猫',
    cap2: '柴犬',
    cap3: '丸子头女孩',
    cap4: '企鹅',
    cap5: '狐狸',
    cap6: '机器人助手',
    footerNote: 'botu · 由 AI 图生图驱动 · 免费、无需注册',
    seoFooter:
      'botu 是免费的在线 bot icon 生成器：上传任意角色图片（头像、插画、宠物照），AI 自动提取发型轮廓、标志配色与关键配饰，生成扁平矢量风格的极简机器人图标（app icon 美学、圆角造型、纯色粉彩背景），支持 PNG 下载。适合做聊天机器人头像、Discord/Telegram bot 图标、应用图标与品牌吉祥物。免费、无需注册。',
  },
  en: {
    seoTitle: 'botu — Bot Icon Generator · Character Image to Minimal Robot Icon, Free Online',
    appTitle: 'botu',
    langBtn: '中文',
    tagline: 'Turn any character image into a minimal bot icon',
    subTagline: 'AI image-to-image · keeps hairstyle silhouette, signature colors & key accessories · ~3-4 min',
    dropTitle: 'drag & drop / paste / click to choose a character image',
    dropHint: 'JPEG · PNG · WebP supported',
    dropActive: 'release to load',
    beforeLabel: 'before',
    afterLabel: 'bot icon',
    idleHint: 'click "generate icon" to start',
    generate: 'generate icon',
    regenerate: 'regenerate',
    download: 'download PNG',
    newImage: 'new image',
    loadingNote: 'generation takes ~3-4 minutes — please keep this page open',
    elapsedFmt: 'elapsed {s}s',
    loadingHints: [
      'reading the character features…',
      'keeping the hairstyle & signature colors…',
      'condensing the cuteness into rounded shapes…',
      'almost there, final polish…',
    ],
    fileMetaFmt: '{w}×{h} · {kb} KB',
    errRead: 'failed to read the image — please try another file',
    errType: 'only JPEG / PNG / WebP images are supported',
    err400: 'bad request (400): unsupported format or invalid input',
    err413: 'image too large (413): please try a smaller one',
    err500: 'server misconfigured (500): generation key missing',
    err502: 'generation failed (502): upstream error, please retry later',
    errNetwork: 'network error or timeout: check your connection and retry',
    errGeneric: 'generation error: {msg}',
    err429: 'daily generation limit reached ({max} per IP per day) — try again tomorrow',
    themeAriaToLight: 'switch to light theme',
    themeAriaToDark: 'switch to dark theme',
    quotaFmt: '{n}/{max} remaining today',
    quotaOut: 'daily limit of {max} reached — come back tomorrow (UTC)',
    galleryTitle: 'gallery · see it in action',
    gallerySub: 'original character on the left, minimal bot icon generated by botu on the right',
    cap1: 'Orange tabby',
    cap2: 'Shiba inu',
    cap3: 'Girl with bun',
    cap4: 'Penguin',
    cap5: 'Fox',
    cap6: 'Robot assistant',
    footerNote: 'botu · powered by AI image-to-image · free, no signup',
    seoFooter:
      'botu is a free online bot icon generator: upload any character image (avatar, illustration, pet photo) and AI extracts the hairstyle silhouette, signature colors and key accessories to produce a minimal flat-vector robot icon (app-icon aesthetic, rounded shapes, clean pastel background) with PNG download. Perfect for chatbot avatars, Discord/Telegram bot icons, app icons and brand mascots. Free, no signup required.',
  },
};

export function detectLang() {
  try {
    const saved = localStorage.getItem('botu-lang');
    if (saved === 'zh' || saved === 'en') return saved;
  } catch {}
  try {
    if ((navigator.language || '').toLowerCase().startsWith('zh')) return 'zh';
  } catch {}
  return 'en';
}

export function applyLang(lang) {
  const d = DICT[lang] || DICT.en;
  try {
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    document.documentElement.dataset.lang = lang;
  } catch {}
  try {
    for (const el of document.querySelectorAll('[data-i18n]')) {
      const v = d[el.dataset.i18n];
      if (typeof v === 'string') el.textContent = v;
    }
  } catch {}
  try {
    document.title = d.seoTitle;
  } catch {}
  try {
    localStorage.setItem('botu-lang', lang);
  } catch {}
  return d;
}
