name = "botu-job-runner"
main = "src/index.js"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BOTU_RL"
id = "5f93916e14d44bf687eaa1afc0ee336c"

[[durable_objects.bindings]]
name = "JOB_RUNNER"
class_name = "JobRunner"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["JobRunner"]
